"""
*2. Fibonacci*
*Intro:* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 0 and 1, the first 7 terms will be: 0 1 1 2 3 5 8

*Problem:* Write a Program to input an integer *X*, and list out the first X terms of the Fibonacci Sequence
"""

print("\nNumber 2")
a = 0
b = 1
nterms = int(input("Enter no of terms: "))
count = 0
while count < nterms:
    print(a)
    count = count + 1
    if count < nterms:
        print(b)
        a = a+b
        b = b+a
        count = count + 1
